arrowParens: avoid
proseWrap: always
singleQuote: true
tabWidth: 4
overrides:
  - files: "*.spec.ts"
    options:
      # Since the tests contain a lot of inline Lua,
      # the higher width generates cleaner code
      printWidth: 120
